# misc info https://www.ii.com/hugo-tips-fragments/#_embed_twitter_list
baseurl = "http://guifreelife.com"
title = "GUI Free Life"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
enableEmoji = true

disablePathToLower = true 
theme = "hugo-universal-theme"

# Enable comments by entering your Disqus shortname
disqusShortname = "dlbewleygithubio"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-78084690-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 2

#[[menu.main]]
#    identifier = "faq"
#    name = "FAQ"
#    url  = "/faq/"
#    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/dlbewley"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitLab"
    url = "https://gitlab.com/dlbewley"
    pre = "<i class='fab fa-2x fa-gitlab'></i>"

[[menu.topbar]]
    weight = 2
    name = "LinkedIn"
    url = "http://linkedin.com/in/dalebewley"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/dlbewley"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "YouTube"
    #url = "http://youtube.com/dlbewley"
    url = "https://www.youtube.com/channel/UCWZw8k_d5U1SeHsMLGY6aIA"
    pre = "<i class='fab fa-2x fa-youtube'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Dale Bewley"
    defaultKeywords = ["bewley", "guifreelife"]
    mainSections = ["blog"]
    defaultDescription = "GUI Free Life"
    # enable page tables of contents
    toc = true

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "dlbewley" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyDacpwSIXi6lk2fS2wzZOSoh7iHm_ZP3UE"

    latitude = "37.802663456"
    longitude = "-122.26916559"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "turquoise"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/mvodpggp"
    contact_form_ajax = false

    about_us = "<p>GUI Free Life is the personal, technical blog of Dale Bewley. Comments and opinions are my own and not that of my employers.</p>"
    copyright = "Copyright (c) 2021, Dale Bewley; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>Dale Bewley</strong>
        <br>Oakland
        <br>California
        <br>
        <strong>USA</strong>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""
#    text = """<p class="hidden-sm hidden-xs">Say hello!</p>
#      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
#      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    toc = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fas fa-tree"
    #icon = "far fa-file-alt"
    #title = "Do you want to see more?"
    #subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "http://guifreelife.com"
    link_text = "GUI Free Life"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Latest from the blog"
#    subtitle = "Latest post from the GUIFREELIFE Blog"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1

  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
      icons = "font"
      sectlinks = true
      sectanchors = true
      source-highlighter = "rouge"
      rouge-css = "style"
      rouge-style = "github"
#      includedir = include
#      experimental = true